name: Playwright Tests with SonarQube

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v2

    # Set up Node.js and install dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before running SonarQube

    steps:
    # Checkout the repository
    - uses: actions/checkout@v2

    # Set up Java (SonarQube requires Java)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Install SonarQube Scanner
    - name: Install SonarQube Scanner
      run: npm install -g sonarqube-scanner

    # Run SonarQube analysis
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # You need to set this secret in your GitHub repository settings
      run: |
        sonar-scanner \
          -Dsonar.projectKey=shreekrishnapandey_playwrightAuto \
          -Dsonar.organization=shreekrishnapandey\
          -Dsonar.sources=tests
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{6f4548e34fbda811533abc2b4c7d9bc0c0870d1b}}
